name: Auto PR from master

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    strategy:
      fail-fast: false
      matrix:
        base_branch:
          - staging2
    uses: ./.github/workflows/create-pr.yml
    with:
      base_branch: ${{ matrix.base_branch }}
      source_branch: master
      pr_title: "Auto PR: Update ${{ matrix.base_branch }} from master"
      pr_body: "This PR was automatically created when master branch was updated."
